Update ci-org-v3.yml

diff --git a/.github/workflows/ci-org-v3.yml b/.github/workflows/ci-org-v3.yml
--- a/.github/workflows/ci-org-v3.yml
+++ b/.github/workflows/ci-org-v3.yml
@@ -46,8 +46,8 @@ jobs:
         uses: actions/checkout@v4
 
       # 2. Configure Git Safe Directory
-      - name: Configure Git Safe Directory
-        run: git config --global --add safe.directory /__w/opencog-central/opencog-central
+#      - name: Configure Git Safe Directory
+#        run: git config --global --add safe.directory /__w/opencog-central/opencog-central
 
       # 3. Install Dependencies
       - name: Install Dependencies
@@ -66,10 +66,10 @@ jobs:
           sudo ldconfig
 
       # 5. Verify CogUtil Installation
-      - name: Verify CogUtil Installation
-        run: |
-          pkg-config --cflags cogutil || { echo "CogUtil not found in pkg-config"; exit 1; }
-          pkg-config --libs cogutil || { echo "CogUtil libraries not found"; exit 1; }
+#      - name: Verify CogUtil Installation
+#        run: |
+#          pkg-config --cflags cogutil || { echo "CogUtil not found in pkg-config"; exit 1; }
+#          pkg-config --libs cogutil || { echo "CogUtil libraries not found"; exit 1; }
 
       # 6. Build and Install AtomSpace
       - name: Build and Install AtomSpace
